default:
  extensions:
    DrevOps\BehatScreenshotExtension: 
      dir: '%paths.base%/../artifacts'
      fail: true
      purge: true
    Behat\MinkExtension:
      browser_name: chrome
      base_url: "https://www.google.com"
      sessions:
        chrome:
          selenium4:
            wd_host: "http://selenium-hub:4444/wd/hub"
            browser: chrome
        firefox:
          selenium4:
            wd_host: "http://selenium-hub:4444/wd/hub"
            browser: firefox
        edge:
          selenium4:
            wd_host: "http://selenium-hub:4444/wd/hub"
            browser: edge
  suites:
    google:
      mink_session: chrome
      paths:
        - '%paths.base%/../scenarios/google'
      contexts:
        - DrevOps\BehatScreenshotExtension\Context\ScreenshotContext: ~
        - Behat\MinkExtension\Context\MinkContext: ~
        - Zozulia\Testsuite\Context\Google\GoogleContext: ~
