name: Selenium test CI pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup environment
        run: make build-env
      - name: Start environment
        run: make start-env
      - name: Wait for selenium hub to be ready
        run: make wait-env
      - name: Start tests
        run: make start-test     
