name: Example Behat test CI pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare environment
        run: make ENV=ci build-env
      - name: Start environment
        run: make ENV=ci start-env
      - name: Wait for environment to be ready
        run: make ENV=ci wait-env
      - name: Run Behat tests
        run: make ENV=ci run-tests
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: artifacts
